# Generated by Django 2.2.9 on 2020-01-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
                ('students_count', models.CharField(max_length=5)),
                ('students_with_grants_count', models.CharField(max_length=5)),
                ('group_leader_name', models.CharField(max_length=20)),
                ('start_lessons_time', models.TimeField()),
            ],
        ),
    ]
