# Generated by Django 2.2.9 on 2020-01-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
    ]
