# Generated by Django 2.2.9 on 2020-01-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_lessons_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
