# Generated by Django 2.2.9 on 2020-01-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200121_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='headman',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_leader_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
