# Generated by Django 2.2.9 on 2020-01-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200122_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_leader_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_leader_name', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='headman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
    ]
