# Generated by Django 2.2.9 on 2020-02-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20200127_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('method', models.IntegerField(choices=[(0, 'Get'), (1, 'Post'), (2, 'Put'), (3, 'Delete')], default=0)),
                ('time_delta', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
