# Generated by Django 2.2.9 on 2020-02-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20200201_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
