# Generated by Django 2.2.9 on 2020-02-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_user_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_platform',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
