# Generated by Django 2.2.9 on 2020-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_logger_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
