# Generated by Django 2.2.9 on 2020-02-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_logger_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='time_delta',
            field=models.CharField(max_length=30),
        ),
    ]
