# Generated by Django 2.2.9 on 2020-02-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20200206_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logger',
            name='method',
            field=models.PositiveIntegerField(choices=[(1, 'GET'), (2, 'POST')]),
        ),
        migrations.AlterField(
            model_name='logger',
            name='path',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='logger',
            name='time_delta',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
